// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetCatalogue.Models;

#nullable disable

namespace ProjetCatalogue.Migrations.GestionFavoriMigrations
{
    [DbContext(typeof(GestionFavori))]
    [Migration("20240503130756_CreerProjetCatalogue")]
    partial class CreerProjetCatalogue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetCatalogue.Models.Favori", b =>
                {
                    b.Property<int>("IdFavori")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFavori"));

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdVideo")
                        .HasColumnType("int");

                    b.Property<string>("PseudoUtilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdFavori");

                    b.HasIndex("IdVideo");

                    b.HasIndex("PseudoUtilisateur");

                    b.ToTable("Favoris", (string)null);

                    b.HasData(
                        new
                        {
                            IdFavori = 7,
                            DateAjout = new DateTime(2023, 9, 22, 10, 11, 51, 0, DateTimeKind.Unspecified),
                            IdVideo = 1,
                            PseudoUtilisateur = "KeyboardCatBobby"
                        },
                        new
                        {
                            IdFavori = 1,
                            DateAjout = new DateTime(2024, 1, 22, 10, 11, 51, 0, DateTimeKind.Unspecified),
                            IdVideo = 4,
                            PseudoUtilisateur = "KeyboardCatBobby"
                        },
                        new
                        {
                            IdFavori = 2,
                            DateAjout = new DateTime(2024, 1, 10, 10, 11, 51, 0, DateTimeKind.Unspecified),
                            IdVideo = 6,
                            PseudoUtilisateur = "KeyboardCatBobby"
                        },
                        new
                        {
                            IdFavori = 3,
                            DateAjout = new DateTime(2023, 9, 22, 10, 11, 51, 0, DateTimeKind.Unspecified),
                            IdVideo = 6,
                            PseudoUtilisateur = "JeSuisJolie93"
                        },
                        new
                        {
                            IdFavori = 4,
                            DateAjout = new DateTime(2023, 9, 22, 11, 11, 51, 0, DateTimeKind.Unspecified),
                            IdVideo = 7,
                            PseudoUtilisateur = "JeSuisJolie93"
                        },
                        new
                        {
                            IdFavori = 5,
                            DateAjout = new DateTime(2023, 9, 22, 12, 11, 51, 0, DateTimeKind.Unspecified),
                            IdVideo = 2,
                            PseudoUtilisateur = "JeSuisJolie93"
                        },
                        new
                        {
                            IdFavori = 6,
                            DateAjout = new DateTime(2023, 9, 22, 9, 11, 51, 0, DateTimeKind.Unspecified),
                            IdVideo = 10,
                            PseudoUtilisateur = "JeSuisJolie93"
                        });
                });

            modelBuilder.Entity("ProjetCatalogue.Models.Utilisateur", b =>
                {
                    b.Property<string>("Pseudo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleUser")
                        .HasColumnType("int");

                    b.HasKey("Pseudo");

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("ProjetCatalogue.Models.Video", b =>
                {
                    b.Property<int>("IdVideo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVideo"));

                    b.Property<string>("Acteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CoteEvaluation")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateMiseEnLigne")
                        .HasColumnType("datetime2");

                    b.Property<double>("DureeVideo")
                        .HasColumnType("float");

                    b.Property<string>("Extrait")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeVideo")
                        .HasColumnType("int");

                    b.Property<string>("VideoComplet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVideo");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("ProjetCatalogue.Models.Favori", b =>
                {
                    b.HasOne("ProjetCatalogue.Models.Video", "Video")
                        .WithMany("Favoris")
                        .HasForeignKey("IdVideo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetCatalogue.Models.Utilisateur", "Utilisateur")
                        .WithMany("Favoris")
                        .HasForeignKey("PseudoUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("ProjetCatalogue.Models.Utilisateur", b =>
                {
                    b.Navigation("Favoris");
                });

            modelBuilder.Entity("ProjetCatalogue.Models.Video", b =>
                {
                    b.Navigation("Favoris");
                });
#pragma warning restore 612, 618
        }
    }
}
