// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetCatalogue.Models;

#nullable disable

namespace ProjetCatalogue.Migrations
{
    [DbContext(typeof(Catalogue))]
    [Migration("20240503130706_CreerProjetCatalogue")]
    partial class CreerProjetCatalogue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetCatalogue.Models.Favori", b =>
                {
                    b.Property<int>("IdFavori")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFavori"));

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdVideo")
                        .HasColumnType("int");

                    b.Property<string>("PseudoUtilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdFavori");

                    b.HasIndex("IdVideo");

                    b.HasIndex("PseudoUtilisateur");

                    b.ToTable("Favori");
                });

            modelBuilder.Entity("ProjetCatalogue.Models.Utilisateur", b =>
                {
                    b.Property<string>("Pseudo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleUser")
                        .HasColumnType("int");

                    b.HasKey("Pseudo");

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("ProjetCatalogue.Models.Video", b =>
                {
                    b.Property<int>("IdVideo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVideo"));

                    b.Property<string>("Acteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CoteEvaluation")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateMiseEnLigne")
                        .HasColumnType("datetime2");

                    b.Property<double>("DureeVideo")
                        .HasColumnType("float");

                    b.Property<string>("Extrait")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeVideo")
                        .HasColumnType("int");

                    b.Property<string>("VideoComplet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVideo");

                    b.ToTable("Videos", (string)null);

                    b.HasData(
                        new
                        {
                            IdVideo = 1,
                            Acteur = "Mr Carrots",
                            Auteur = "Polo Paulson",
                            CoteEvaluation = -1.0,
                            DateMiseEnLigne = new DateTime(2010, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DureeVideo = 0.28000000000000003,
                            Extrait = "1.mp4",
                            Image = "1.jpeg",
                            Titre = "Funny Bunny",
                            TypeVideo = 7,
                            VideoComplet = "1.mp4"
                        },
                        new
                        {
                            IdVideo = 2,
                            Acteur = "Grumpy Cat",
                            Auteur = "Tamara Tamarin",
                            CoteEvaluation = -1.0,
                            DateMiseEnLigne = new DateTime(2017, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DureeVideo = 1.27,
                            Extrait = "2.mp4",
                            Image = "2.jpeg",
                            Titre = "Grumpy Cat on a talk show",
                            TypeVideo = 1,
                            VideoComplet = "2.mp4"
                        },
                        new
                        {
                            IdVideo = 3,
                            Acteur = "Grumpy Cat",
                            Auteur = "Tamara Tamarin",
                            CoteEvaluation = -1.0,
                            DateMiseEnLigne = new DateTime(2019, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DureeVideo = 1.0,
                            Extrait = "3.mp4",
                            Image = "3.jpeg",
                            Titre = "Grumpy Cat's first pitch",
                            TypeVideo = 1,
                            VideoComplet = "3.mp4"
                        },
                        new
                        {
                            IdVideo = 4,
                            Acteur = "Jean-Guy le furet",
                            Auteur = "Mick McMac",
                            CoteEvaluation = -1.0,
                            DateMiseEnLigne = new DateTime(2012, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DureeVideo = 1.28,
                            Extrait = "4.mp4",
                            Image = "4.jpeg",
                            Titre = "Playful ferret",
                            TypeVideo = 15,
                            VideoComplet = "4.mp4"
                        },
                        new
                        {
                            IdVideo = 5,
                            Acteur = "FoxyFox",
                            Auteur = "Tommy Tomtoms",
                            CoteEvaluation = -1.0,
                            DateMiseEnLigne = new DateTime(2019, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DureeVideo = 0.52000000000000002,
                            Extrait = "5.mp4",
                            Image = "5.jpeg",
                            Titre = "Fox likes attention",
                            TypeVideo = 12,
                            VideoComplet = "5.mp4"
                        },
                        new
                        {
                            IdVideo = 6,
                            Acteur = "Keyboard Cat",
                            Auteur = "Michelle Michels",
                            CoteEvaluation = -1.0,
                            DateMiseEnLigne = new DateTime(2019, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DureeVideo = 0.54000000000000004,
                            Extrait = "6.mp4",
                            Image = "6.jpeg",
                            Titre = "Keyboard Cat",
                            TypeVideo = 1,
                            VideoComplet = "6.mp4"
                        },
                        new
                        {
                            IdVideo = 7,
                            Acteur = "Mc Roach",
                            Auteur = "Georgio Georges",
                            CoteEvaluation = -1.0,
                            DateMiseEnLigne = new DateTime(2010, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DureeVideo = 0.20999999999999999,
                            Extrait = "7.mp4",
                            Image = "7.jpeg",
                            Titre = "Big Insect",
                            TypeVideo = 9,
                            VideoComplet = "7.mp4"
                        },
                        new
                        {
                            IdVideo = 8,
                            Acteur = "Miss Muffin",
                            Auteur = "Stella Steel",
                            CoteEvaluation = -1.0,
                            DateMiseEnLigne = new DateTime(2013, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DureeVideo = 1.3799999999999999,
                            Extrait = "8.mp4",
                            Image = "8.jpeg",
                            Titre = "Rabbit eats lemon",
                            TypeVideo = 7,
                            VideoComplet = "8.mp4"
                        },
                        new
                        {
                            IdVideo = 9,
                            Acteur = "Robber Raccoon",
                            Auteur = "Yan YinYang",
                            CoteEvaluation = -1.0,
                            DateMiseEnLigne = new DateTime(2008, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DureeVideo = 1.0,
                            Extrait = "9.mp4",
                            Image = "9.jpeg",
                            Titre = "Raccoon steals carpet",
                            TypeVideo = 5,
                            VideoComplet = "9.mp4"
                        },
                        new
                        {
                            IdVideo = 10,
                            Acteur = "One Small marmot",
                            Auteur = "Albert Albertson",
                            CoteEvaluation = -1.0,
                            DateMiseEnLigne = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DureeVideo = 2.3399999999999999,
                            Extrait = "10.mp4",
                            Image = "10.jpeg",
                            Titre = "Marmot gets a bath",
                            TypeVideo = 6,
                            VideoComplet = "10.mp4"
                        });
                });

            modelBuilder.Entity("ProjetCatalogue.Models.Favori", b =>
                {
                    b.HasOne("ProjetCatalogue.Models.Video", "Video")
                        .WithMany("Favoris")
                        .HasForeignKey("IdVideo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetCatalogue.Models.Utilisateur", "Utilisateur")
                        .WithMany("Favoris")
                        .HasForeignKey("PseudoUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("ProjetCatalogue.Models.Utilisateur", b =>
                {
                    b.Navigation("Favoris");
                });

            modelBuilder.Entity("ProjetCatalogue.Models.Video", b =>
                {
                    b.Navigation("Favoris");
                });
#pragma warning restore 612, 618
        }
    }
}
