// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetCatalogue.Models;

#nullable disable

namespace ProjetCatalogue.Migrations
{
    [DbContext(typeof(GestionUtilisateur))]
    [Migration("20240501140027_CreerProjetCatalogue")]
    partial class CreerProjetCatalogue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetCatalogue.Models.Utilisateur", b =>
                {
                    b.Property<string>("Pseudo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleUser")
                        .HasColumnType("int");

                    b.HasKey("Pseudo");

                    b.ToTable("Cours", (string)null);

                    b.HasData(
                        new
                        {
                            Pseudo = "KeyboardCatBobby",
                            MotDePasse = "Soleil01!",
                            Nom = "McBob",
                            Prenom = "Bobby",
                            RoleUser = 0
                        },
                        new
                        {
                            Pseudo = "JeSuisJolie93",
                            MotDePasse = "Soleil01!",
                            Nom = "Bobinson",
                            Prenom = "Maritza",
                            RoleUser = 0
                        },
                        new
                        {
                            Pseudo = "adminPrincipal",
                            MotDePasse = "Soleil01!",
                            Nom = "Rogers",
                            Prenom = "Roger",
                            RoleUser = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
