// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetCatalogue.Models;

#nullable disable

namespace ProjetCatalogue.Migrations.GestionUtilisateurMigrations
{
    [DbContext(typeof(GestionUtilisateur))]
    partial class GestionUtilisateurModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetCatalogue.Models.Favori", b =>
                {
                    b.Property<int>("IdFavori")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFavori"));

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdVideo")
                        .HasColumnType("int");

                    b.Property<string>("PseudoUtilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdFavori");

                    b.HasIndex("IdVideo");

                    b.HasIndex("PseudoUtilisateur");

                    b.ToTable("Favori");
                });

            modelBuilder.Entity("ProjetCatalogue.Models.Utilisateur", b =>
                {
                    b.Property<string>("Pseudo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleUser")
                        .HasColumnType("int");

                    b.HasKey("Pseudo");

                    b.ToTable("Utilisateurs", (string)null);

                    b.HasData(
                        new
                        {
                            Pseudo = "KeyboardCatBobby",
                            MotDePasse = "Soleil01!",
                            Nom = "McBob",
                            Prenom = "Bobby",
                            RoleUser = 0
                        },
                        new
                        {
                            Pseudo = "JeSuisJolie93",
                            MotDePasse = "Soleil01!",
                            Nom = "Bobinson",
                            Prenom = "Maritza",
                            RoleUser = 0
                        },
                        new
                        {
                            Pseudo = "adminPrincipal",
                            MotDePasse = "Soleil01!",
                            Nom = "Rogers",
                            Prenom = "Roger",
                            RoleUser = 2
                        });
                });

            modelBuilder.Entity("ProjetCatalogue.Models.Video", b =>
                {
                    b.Property<int>("IdVideo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVideo"));

                    b.Property<string>("Acteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CoteEvaluation")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateMiseEnLigne")
                        .HasColumnType("datetime2");

                    b.Property<double>("DureeVideo")
                        .HasColumnType("float");

                    b.Property<string>("Extrait")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeVideo")
                        .HasColumnType("int");

                    b.Property<string>("VideoComplet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVideo");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("ProjetCatalogue.Models.Favori", b =>
                {
                    b.HasOne("ProjetCatalogue.Models.Video", "Video")
                        .WithMany("Favoris")
                        .HasForeignKey("IdVideo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetCatalogue.Models.Utilisateur", "Utilisateur")
                        .WithMany("Favoris")
                        .HasForeignKey("PseudoUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("ProjetCatalogue.Models.Utilisateur", b =>
                {
                    b.Navigation("Favoris");
                });

            modelBuilder.Entity("ProjetCatalogue.Models.Video", b =>
                {
                    b.Navigation("Favoris");
                });
#pragma warning restore 612, 618
        }
    }
}
